### ISSUE TITLE
Also publish on Open VSX Registry?

### ISSUE THREAD

**Issue by PeterDaveHello** [Christopher-Hayes/vscode-chatgpt-reborn#12]
### Describe the feature

I originally found gencay's vscode-chatgpt here: https://open-vsx.org/extension/gencay/vscode-chatgpt, and noticed that this reborn fork currently is only available on the Visual Studio Marketplace, would you also consider publishing it on the Open VSX Registry (https://open-vsx.org/) just like the original one?

The Open VSX Registry is an open-source registry for VSCode extensions that provides an alternative to the Visual Studio Marketplace. It's gaining popularity among developers who want to avoid the limitations of the Marketplace, such as slower reviews and more restricted publication policies. (according to GPT-4 😆)

Thank you for your time to maintain this reborn and consideration!

**Comment by Christopher-Hayes** [comment]
Thanks @PeterDaveHello, I wasn't aware of it. Will do!

**Comment by Christopher-Hayes** [comment]
Published! https://open-vsx.org/extension/chris-hayes/chatgpt-reborn

Working on reserving the namespace to remove the verified warning.

**Comment by PeterDaveHello** [comment]
Awesome, thanks Chris! (Also good to see the link is already added in the README 👍 )
