### ISSUE TITLE
Page Experience

### ISSUE THREAD

**Issue by niubg** [Christopher-Hayes/vscode-chatgpt-reborn#13]
### Describe the feature

The current UI layout and code prompts highlight themes that are difficult to accept, preferring the original version's UI style. Currently, it seems that the layout is cluttered and cannot quickly focus on important content areas. I hope to do some balancing on the UI

**Comment by niubg** [comment]
I think the following pages will be more concise and convenient to use：

![image](https://user-images.githubusercontent.com/50099479/227699228-652b4bce-5dfa-4c83-ae4b-ec1540cc9196.png)


The new version of the page takes up too much operating space

![image](https://user-images.githubusercontent.com/50099479/227699200-50972c19-3045-4273-a686-a079e5590b43.png)

**Comment by Christopher-Hayes** [comment]
Thank you for the feedback @niubg, I've added 2 config options in the latest release (v3.11.5), `disableMultipleConversations` which will hide the chat tabs, as well as `minimalUI` which removes both the chat tabs and the buttons at the bottom. `minimalUI` will also hide any future UI additions.

I'll keep UI clutter in mind as I make future UI updates.

**Comment by Christopher-Hayes** [comment]
Just released `v3.12.0` which consolidates some of the less used buttons at the bottom into a menu.
![image](https://user-images.githubusercontent.com/6013871/227770676-f8a67cd0-2ca9-4093-a485-21d4286f1a3f.png)
