### ISSUE TITLE
Option to start new conversation

### ISSUE THREAD

**Issue by Darkmift** [Christopher-Hayes/vscode-chatgpt-reborn#15]
### Describe the feature

Hi,

Until recently the UI had the option to start a new conversation which now seems to be missing in the new UI from these past few days

![image](https://user-images.githubusercontent.com/12433441/227732392-829ea799-4b08-49ba-827d-a2033722d219.png)

I default to use it from time to time when the AI answers become erratic

**Comment by Christopher-Hayes** [comment]
Thank you for the bug report @Darkmift. So the dropdown part is what the tabs look like when the chatgpt window is below a certain width. I forgot to update the code for tabs at that width.

I've just published `v3.11.3` which fixes this bug and refines the tab UI.

**Comment by Christopher-Hayes** [comment]
A new release will also be seeing this new menu for less commonly used actions.
![image](https://user-images.githubusercontent.com/6013871/227769672-63a1de23-d84d-4964-b999-ecb678ac19de.png)

**Comment by Darkmift** [comment]
Amazing,
This plugin is an amazing companion!
