### ISSUE TITLE
Set `chatgpt.gpt3.maxTokens` = `4096` with `gpt-3.5-turbo` will always recive `400 Bad Request`

### ISSUE THREAD

**Issue by PeterDaveHello** [Christopher-Hayes/vscode-chatgpt-reborn#16]
### Describe the Bug

According to the document: https://platform.openai.com/docs/models/gpt-3-5, Max tokens of `gpt-3.5-turbo` is 4096, however, when I set `chatgpt.gpt3.maxTokens` to `4096`, no matter how short my code is, I got 400 Bad Request.

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

Using OpenAI API Key with model `gpt-3.5-turbo`, and customized maxTokens to 4096

### Additional context

I tried to set it to from `3800` to `4000`, the problem is still there, but `3750` starts to look good to me right now, in some cases, it need to be lower, but the code is actually too short to make the token not enough(only a few lines, for testing purpose), that's very interesting.

**Comment by PeterDaveHello** [comment]
BTW, I'm not sure the the reason why, but even my code isn't that long, I can send it to `gpt-3.5-turbo` with other method, using the same context and prompt message to ask OpenAI to optimize the code, but it's a lot easier to get `400 Bad Request` via the plugin.

**Comment by PeterDaveHello** [comment]
Thanks, the interesting part is the code to test has no chance to be more than a hundred tokens, it's very very short, and simply change the config can make it works or not, that's why I think it's a bug 😅

**Comment by Christopher-Hayes** [comment]
@PeterDaveHello Thanks again for the report, this issue should be fixed in `v3.14.0`.

With GPT-4 being 30x more expensive than GPT-3.5 and the token usage increasing as the conversation gets longer, `v3.14.0` will also have include the "token count" to help keep an eye on token usage.

**Comment by PeterDaveHello** [comment]
Thank you @Christopher-Hayes for the upates, will take some time to test them and see if all work as expect 😁
