### ISSUE TITLE
Organization ID

### ISSUE THREAD

**Issue by gh-assan** [Christopher-Hayes/vscode-chatgpt-reborn#25]
### Describe the Bug

Hey,
how can I set Organization ID ? 

### Where are you running VSCode? (Optional)

MacOS

### Which OpenAI model are you using? (Optional)

gpt-4

**Comment by Christopher-Hayes** [comment]
Hey @gh-assan, it should be there in the extension settings. If you click on "More Actions" > "Settings", in the VSCode Settings UI you should see "Organization" in there with the description "OpenAI Organization ID". If that config setting isn't working, LMK.

**Comment by gh-assan** [comment]
it works only after removing Genie extension
