### ISSUE TITLE
There is a problem with the installation, suggesting that this version of VScode is not compatible

### ISSUE THREAD

**Issue by zzy-life** [Christopher-Hayes/vscode-chatgpt-reborn#30]
### Describe the Bug

![image](https://user-images.githubusercontent.com/68179477/235359890-452fcd31-d318-4210-8d48-e5a68754c35a.png)

### Where are you running VSCode? (Optional)

Windows

### Which OpenAI model are you using? (Optional)

gpt-3.5-turbo

**Comment by Christopher-Hayes** [comment]
It was previously set at `v1.73.0` as the minimum required version. I've lowered it to `v1.70.0`, it should still work fine.

I'm only testing on the latest version of VSCode, so I'm unable to confirm which older versions of VSCode work and which ones do not.

This update will ship in the next release.

**Comment by Christopher-Hayes** [comment]
This update has been pushed in release `v3.16.3`.
