### ISSUE TITLE
"Add comments" command in context menu is "Add tests"

### ISSUE THREAD

**Issue by wojtekcz** [Christopher-Hayes/vscode-chatgpt-reborn#48]
### Describe the Bug

<img width="492" alt="image" src="https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/1236889/deffda23-6f8c-487c-b0f9-9a7fd48caf11">

"ChatGPT: Add tests" text in context menu should be "ChatGPT: Add comments" - as this line executes "Add comments" command.

### Where are you running VSCode? (Optional)

MacOS

### Which OpenAI model are you using? (Optional)

None

**Comment by Christopher-Hayes** [comment]
Oops. Thank you for the report.

**Comment by Christopher-Hayes** [comment]
Fixed in [v3.19.0](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/releases/tag/3.19.0), thank you again.
