### ISSUE TITLE
Move context menu items into menu

### ISSUE THREAD

**Issue by Christopher-Hayes** [Christopher-Hayes/vscode-chatgpt-reborn#51]
### Describe the feature

GitHub's Copilot has similar context menu items to our extension. Except they put it inside a menu to avoid polluting the context menu too much. I think this would be a good idea for this extension to adopt as well. 

Copilot
![Screenshot of copilot's context menu items - neatly inside a menu.](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/6013871/dbb07e95-011d-4de4-b953-65da8c00d2ae)

Reborn
![Screenshot of reborn's context menu items - they take up a lot of space.](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/6013871/43945b1a-e76b-4946-879a-5f91066b3b87)

This would also allow us to remove the "ChatGPT: " prefix, which would make it more readable as well.

**Comment by SergioSuarezDev** [comment]
+1 I found this extension today and i love it. Would be nice add all menu items inside one Chatgpt context menu, to create a submenu of actions

<img width="550" alt="263007502-711e44f0-5f4c-4b88-a4e0-ad0fa46394de" src="https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/3636232/27aa353a-64c6-4995-9b07-10a67b674997">

**Comment by Christopher-Hayes** [comment]
This update has been pushed in the latest release, `v3.20.1`: https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/releases/tag/3.20.1

Thanks for the example @SergioSuarezDev

**Comment by SergioSuarezDev** [comment]
super! thanks, downloading now
