### ISSUE TITLE
Provide gpt-4 model selection in the More Actions interface

### ISSUE THREAD

**Issue by rambalachandran** [Christopher-Hayes/vscode-chatgpt-reborn#53]
### Describe the Bug

gpt-4 model has been made generally available. So, it will be helpful if this is provided directly in the More Actions interface to be able to select alongside gpt-3.5-turbo and gpt-3.5-turbo-16K

### Where are you running VSCode? (Optional)

Linux

### Which OpenAI model are you using? (Optional)

None

**Comment by Christopher-Hayes** [comment]
@rambalachandran  You aren't able to switch it now? There should be a button at the bottom left.

![image](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/6013871/75207202-a709-4190-9f35-22ac9cd7cdee)

When the UI is not as wide, you'll find it in the "more actions" menu.

![image](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/6013871/f293c701-cac5-405e-a7ce-a5f57907199a)

GPT-3.5-turbo 16k is also available.

![image](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/6013871/2394ec58-e6f7-4e54-a457-c8e1dc1dd929)

**Comment by rambalachandran** [comment]
This is how my More Action menu looks like

![image](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/6717520/029c692c-29f6-4f22-8754-d7fb4c5d1097)

**Comment by Christopher-Hayes** [comment]
> @Christopher-Hayes This is how my More Action menu looks like
> 
> ![image](https://user-images.githubusercontent.com/6717520/263884213-029c692c-29f6-4f22-8754-d7fb4c5d1097.png)

That means your API key does not have access to GPT-4. The OpenAI /models API endpoint is used to check which models the API key has access to.

**Comment by rambalachandran** [comment]
Apologies yes the API Key I was using did not have gpt4 access. When I changed keys with gpt4 access it worked. Thank you. Closing the ticket

**Comment by Christopher-Hayes** [comment]
No problem, glad you got it working.
