### ISSUE TITLE
Improve cost overview

### ISSUE THREAD

**Issue by moritz-t-w** [Christopher-Hayes/vscode-chatgpt-reborn#58]
### Describe the feature

![current](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/90388353/066e2a51-dfeb-4924-9533-36b82c1f3d5c)
The way I would interpret this is that fewer checks means lower cost, just like fewer quality checks means lower quality.
I feel like usually in an overview like this prices would be conveyed using dollar signs, so I propose to use that convention, instead of something ambiguous like checkmarks.
Maybe something like this:
![mockup](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/90388353/c1c59e59-2c62-4f13-9171-c0e87dbdb4ca)

**Comment by Christopher-Hayes** [comment]
That's a good idea, thanks @moritz-t-w. I'll get that added.

**Comment by Christopher-Hayes** [comment]
The latest release has this update @moritz-t-w, thanks again for the suggestion. I did use a slightly different money emoji because some OS's use a black dollar sign which would be a problem for dark themes.
