### ISSUE TITLE
chatgpt.gpt3.apiBaseUrl setting not working after v3.20.0

### ISSUE THREAD

**Issue by nossebro** [Christopher-Hayes/vscode-chatgpt-reborn#63]
I am using [oobabooga's text-generation-webui](https://github.com/oobabooga/text-generation-webui) with its openai extension to serve local llms for ChatGPT Reborn to use.

The only setting I have changed is `"chatgpt.gpt3.apiBaseUrl": "http://127.0.0.1:5000/v1"`, and I have provided [my own API key](https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API#starting-the-api)

Versions [v3.20.0](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/releases/tag/3.20.0) works correctly.

Maybe this is to blame: https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/blame/41107ed508a050d42d995c06334ca1279c7c4f3d/src/api-provider.ts#L34

**Comment by Christopher-Hayes** [comment]
Thanks for the report, will take a look. OpenAI made breaking changes to their API schema to support GPTs and it looks like proxies broke in the process of updating to support the new API schema.

**Comment by Christopher-Hayes** [comment]
Fixed in `v3.23.0`
