### ISSUE TITLE
Check for existing punctuation mark before adding "." to prompt

### ISSUE THREAD

**Issue by moritz-t-w** [Christopher-Hayes/vscode-chatgpt-reborn#65]
### Describe the feature

When you add the Editor selection it always adds a "." at the end of your prompt. I think it should check if you already have a "." "?" or "!"

**Comment by moritz-t-w** [comment]
Actually I'm not able to reproduce this anymore but I swear it was a thing til like a week ago

**Comment by Christopher-Hayes** [comment]
probably related to the fact that when you hit the "editor selection" it will then focus the "ask a question" input field. This was done to save a mouse click. It doesn't add punctuation, that would likely be coming from your operating system, usually that's done after a space, not when a input field is focused. So, I'm not 100% why that was happening.
