### ISSUE TITLE
HTTP 500 Error during API auth

### ISSUE THREAD

**Issue by Whytehorse2022** [Christopher-Hayes/vscode-chatgpt-reborn#7]
### Describe the Bug

 I tried the new extension, I added my API key, and it gives the error:
`The server had an error while processing your request, please try again. (HTTP 500 Internal Server Error)
See https://platform.openai.com/docs/guides/error-codes for more details.

ChatGPT error 500: {
"error": {
"message": "Internal server error",
"type": "auth_subrequest_error",
"param": null,
"code": "internal_error"
}
}`

Steps to reproduce:
1. Install the extension from the marketplace
2. Open the extension
3. Type "hello"
4. Enter API key into the popup

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

All defaults

**Comment by drupol** [comment]
Bravo!

**Comment by Christopher-Hayes** [comment]
Thank you, @Whytehorse2022, OpenAI is currently experiencing a major outage for their GPT-3/4 API. I'm now having issues on my end as well, so I'd suggest waiting a bit and trying when OpenAI is back online to see if that resolves the issue for you.

https://status.openai.com/

**Comment by Whytehorse2022** [comment]
I understand. This doesn't seem like a bug in your code. I will try again tomorrow. I recall recently learning about a javascript method/library that uses async and promises. Maybe throwing that into the mix with a watchdog timer would make the extension more robust(e.g. blame the server). https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

We use it with JSON requests so I don't know if it will translate to your code or not.

**Comment by Christopher-Hayes** [comment]
Yeah, a more helpful message would be a good idea.

**Comment by Whytehorse2022** [comment]
> Yeah, a more helpful message would be a good idea.
Oh I see what you mean. Like the extension could say something like "We're encountering errors connecting to chatGPT servers. Please check https://status.openai.com/ to see if this is a known issue. If not, please report this at https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/issues/" or something like that. 

Anyway I'll check again tomorrow and if the problem is fixed I'll close this issue. Is there some way to set a remindme type of thing?

**Comment by Christopher-Hayes** [comment]
The API is back up now for me. So, whenever you want to, GitHub doesn't have any type of reminder feature.

**Comment by Whytehorse2022** [comment]
It works now. Bug closed.

**Comment by Whytehorse2022** [comment]
If I change to GPT 4 model I get a 404 error:
Your method: 'GPT3 OpenAI API Key' and your model: 'gpt-4' may be incompatible or you may have exhausted your ChatGPT subscription allowance. (HTTP 404 Not Found)

ChatGPT error 404: {
"error": {
    "message": "The model: `gpt-4` does not exist",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
}
}

**Comment by drupol** [comment]
This is another issue...

**Comment by Christopher-Hayes** [comment]
@Whytehorse2022 are you sure your API key has access to GPT-4? You would've had to signed up on the OpenAI GPT-4 waitlist and then received an email that you now have access. You can check by going to the [OpenAI Playground](https://platform.openai.com/playground?mode=chat), if you have access to GPT-4, then GPT-4 will appear in the "model" dropdown list.

**Comment by Whytehorse2022** [comment]
OK, I got on the waitlist. Will test once I'm able. In the meantime the gpt-3.5-turbo is working great. Thanks for this awesome extension. I was using gpt4 with the old extension and no api, just my email. Is that why it violated the terms of service? Maybe I was using someone else's API key?

**Comment by Christopher-Hayes** [comment]
@Whytehorse2022 iirc the old extension only allowed you to use GPT-4 if you were using the browser login method, that login method being the reason the extension was discontinued. I imagine other forks are going to try to keep the browser login part running, but for this fork I'll be focusing on just the API.

**Comment by Christopher-Hayes** [comment]
Since it is working for you again, I'll close this issue. If you have new issues or feature requests, feel free to create a new GitHub issue. I'll try to make time to include additional messaging about the availability of GPT-4 in the extension.

**Comment by Whytehorse2022** [comment]
Thanks. I was going to close it. Would you like me to open another issue for the 404 API error, post the solution discussed here, and then close it so the search engines direct all that stuff over there?

**Comment by Christopher-Hayes** [comment]
@Whytehorse2022 no need, this issue will come up in search.
