### ISSUE TITLE
Feature request: Secure API key storage (not plaintext in settings.json)

### ISSUE THREAD

**Issue by flutterrausch** [Christopher-Hayes/vscode-chatgpt-reborn#8]
### Describe the feature

CodeGPT supposedly does this (did not try).

**Comment by Christopher-Hayes** [comment]
Thank you for the feature request @flutterrausch. `v3.12.0` now uses VSCode secure storage. If your API key is in your Settings.json now, it will be automatically moved into secure storage and wiped from your settings when you launch `v3.12.0` for the first time.
